// src/components/ColorPickerModal.svelte
<script>
  import { colorTable as colors } from "../utils/colors.js";
  import { createEventDispatcher } from "svelte";

  const dispatch = createEventDispatcher();

  export let colorKeys = Object.keys(colors);
  export let colorKey = null;
  let isOpen = false;

  function selectColor(colorKey) {
    dispatch("selectColor", colorKey);
    isOpen = false;
  }

  $: if (colorKey) {
    isOpen = true;
  }
</script>

{#if isOpen}
  <div class="modal">
    {#each colorKeys as key}
      <div
        class="color-option"
        style="background-color: {colors[key]}"
        on:click={() => selectColor(key)}
      />
    {/each}
  </div>
{/if}

<style>
  .modal {
    z-index: 1000;
    position: fixed;
    top: 0;
    left: 0;
    width: 100vw;
    height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    background-color: rgba(0, 0, 0, 0.8);
    flex-wrap: wrap;
  }

  .color-option {
    display: inline-block;
    width: 50px;
    height: 50px;
    margin: 5px;
    flex-shrink: 0;
    cursor: pointer;
    transition: all 0.5s;
  }

  .color-option:hover {
    scale: 1.2;
  }
</style>

// src/components/ColorPickerModal.vue
<script setup lang="ts">
import { colorTable } from "../utils/colors";
</script>

<template>
  <div class="flex flex-wrap gap-2 justify-center z-10 absolute top-0 left-0">
    <div
      v-for="(value, name, index) in colorTable"
      class="w-10 h-10 border border-black transition-all cursor-pointer hover:scale-125"
      :name="name"
      :style="`background-color: ${value}`"
    ></div>
  </div>
</template>
